auth/urls.py
from django.urls import path
from auth import views

urlpatterns = [

        path('login/', views.Login.as_view(), name="login"),
        path('signup/', views.Signup.as_view(), name="signup"),
        path('logout/', views.Logout.as_view(), name="logout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your models here.

class Shop(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shop_name = models.CharField(max_length=250, blank=False, null=False)

    def __str__(self):
        return self.shop_name

class Category(models.Model):
    category_name = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.category_name

class Item(models.Model):
    item_name = models.CharField(max_length=250, null=False, blank=False)
    item_image = models.ImageField(blank=True, null=True)
    item_price = models.FloatField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    item_description = models.TextField(null=False, blank=False )
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE)

    def __str__(self):
        return self.item_name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item_id = models.ForeignKey('Item', on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True)
    total_amount = models.FloatField()

    def __str__(self):
        return self.item_id.item_name

class Order(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    item_id = models.ForeignKey('Item', on_delete=models.CASCADE, related_name="order_item")
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    quantity = models.IntegerField()
    shop_id = models.ForeignKey('Shop', on_delete=models.CASCADE, related_name="shop_item")
    purchase_date = models.DateTimeField(auto_now_add=True)
    total_price = models.FloatField()
    shipping_address = models.TextField(max_length=500)
    pincode = models.IntegerField()
    mobile_no = models.IntegerField()
    
    def __str__(self):
        return self.item_id.item_name
    
    

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" >
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">E-commerce</a>
      {% if request.user.is_authenticated %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
         
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for category in categories %}
              {% ifchanged %}
              <li><a class="dropdown-item" href="{% url 'items' category.id %}">{{category.category_name}}</a></li>
              {% endifchanged %}
              {% endfor %}
            </ul>
          </li> 
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'orders' %}">Orders</a>
          </li>
          <li class="nav-item">
            {% if request.user.shop_set.all %}
            <a class="nav-link active" aria-current="page" href="{% url 'shop_items'%}">Your Shop</a>
            {% else %}
            <a class="nav-link active" aria-current="page" href="{% url 'create_shop'%}">Sell on E-commerce</a>
            {% endif %}
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
       
        <div class="text-white fw-bold ">Hello, {{user.first_name }} {{user.last_name}}</div>&nbsp;&nbsp;
       
       <div>
        
       <a href="/cart/" class="position-relative">
          <i class="fas fa-shopping-cart" style="color: white; font-size:30px;"></i>
          <span class="position-absolute start-100 translate-middle badge rounded-pill bg-danger">
            <span id="cart_count">{{cart_count}}</span>
            <span class="visually-hidden">unread messages</span>
          </span>
        </a>
       </div>&nbsp;&nbsp; 
      </div>
      {% else %}
     
       <p class="fw-bold  ecom_greet">Welcome to Ecommerce</p>
       <ul class="navbar-nav mx-5">
        <li class="">
          <a class="nav-link active fs-5" aria-current="page" href="{% url 'login' %}">LogIn</a>
        </li>
      </ul>
      {% endif %} 
    </div>
  </nav>